//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

         
// USER INCLUDES			
#include <SI_EFM8BB2_Register_Enums.h>
#include "InitDevice.h"
//-----------------------------------------------------------------------------
// Global CONSTANTS
//-----------------------------------------------------------------------------
#define UART_BUFFERSIZE        64

//-----------------------------------------------------------------------------
// Global Variables
//-----------------------------------------------------------------------------
//uint8_t UART_Buffer[UART_BUFFERSIZE];

//uint8_t UART_Buffer_Size = 0;
//uint8_t UART_Input_First = 0;
//uint8_t UART_Output_First = 0;
//uint8_t TX_Ready =1;
//uint8_t Byte = 0;

uint16_t INT0Timeh = 0;

uint16_t INT0TimehSum = 0;

extern uint8_t hptype_on;
uint16_t INT0Count=0;
uint8_t INT1FirstEnterFlag=0;
uint8_t INT0StartCountFlag=0;
extern uint8_t VolumeDownFlag;
extern uint8_t VolumeUpFlag;
extern void serial_service_rx(void);
extern void TIM2_Cmd(char NewState);
extern void timer2_service(void);
//extern void delay_ms(unsigned int mdelay);
//-----------------------------------------------------------------------------
// UART0_ISR
//-----------------------------------------------------------------------------
//
// UART0 ISR Content goes here. Remember to clear flag bits:
// SCON0::RI (Receive Interrupt Flag)
// SCON0::TI (Transmit Interrupt Flag)
//
// This routine is invoked whenever a character is entered or displayed on the
// Hyperterminal.
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (UART0_ISR, UART0_IRQn)
{
	   if (SCON0_RI == 1)
	   {
	      //if( UART_Buffer_Size == 0)  {    // If new word is entered
	      //   UART_Input_First = 0;    }

	      SCON0_RI = 0;                          // Clear interrupt flag
        serial_service_rx();
	      //Byte = SBUF0;                    // Read a character from UART

	     /* if (UART_Buffer_Size < UART_BUFFERSIZE)
	      {
	         UART_Buffer[UART_Input_First] = Byte; // Store in array

	         UART_Buffer_Size++;           // Update array's size

	         UART_Input_First++;           // Update counter
	      }*/
	   }

	 /*  if (SCON0_TI == 1)                        // Check if transmit flag is set
	   {
	      SCON0_TI = 0;                          // Clear interrupt flag

	      if (UART_Buffer_Size != 1)       // If buffer not empty
	      {
	         // If a new word is being output
	         if ( UART_Buffer_Size == UART_Input_First ) {
	              UART_Output_First = 0;  }

	         // Store a character in the variable byte
	         Byte = UART_Buffer[UART_Output_First];

	       //  if ((Byte >= 0x61) && (Byte <= 0x7A)) { // If upper case letter
	       //     Byte -= 32; }

	         SBUF0 = Byte;                 // Transmit to Hyperterminal

	         UART_Output_First++;          // Update counter

	         UART_Buffer_Size--;           // Decrease array size

	      }
	      else
	      {
	         UART_Buffer_Size = 0;         // Set the array size to 0
	         TX_Ready = 1;                 // Indicate transmission complete
	      }
	   }*/
}

SI_INTERRUPT (TIMER2_ISR, TIMER2_IRQn)
{
	//static uint16_t count_ms = 0;
	//count_ms += 1;

/*	if (count_ms == LED1_TOGGLE_RATE)
	{
		LED1 = !LED1;  // Toggle the LED
		count_ms = 0;
	}*/
  timer2_service();
	TMR2CN0_TF2H = 0;  // Clear the interrupt flag
}



SI_INTERRUPT (INT1_ISR, INT1_IRQn)
{
 IE_EX1=0;
 // 
 if(INT1FirstEnterFlag==0)
 	   INT1FirstEnterFlag=1;
 else	   
   SELECT=0;
  //if(hptype_on==2)
   	{
   while(1)
   {
   	if(HP_TYPE==1)
   		  {break;
   		  }
   	}
   }
   	 SELECT=1;
  
  IE_EX1=1; 	 
}



SI_INTERRUPT (INT0_ISR, INT0_IRQn)
{
	//IE_EX0=0;

   	 while(VOLUMEIN)
   	 {
   	 	INT0Timeh++;
   	}
   	if(INT0Timeh==0)
   		 {
   		 	goto INT_RELEASE;
   		}
   	//	if(INT0StartCountFlag==0)
   		//INT0StartCountFlag=1;
   		INT0Count++;
   	/*	if((INT0Count>=120)&&(INT0Count<150))
   			{INT0TimehSum+=INT0Timeh;
   			}
   		if(INT0Count==150)
   				{
   					if((INT0TimehSum>70)&&(INT0TimehSum<90))
   						{VOLUMEUP=0;
  	     	     VolumeUpFlag=1;
   						}
   					else if((INT0TimehSum>100)&&(INT0TimehSum<120))
   						{VOLUMEDOWN=0;
  	     	     VolumeDownFlag=1;
   						}	
   					else 
   						INT0TimehSum=0;	
   				}	*/
   				
   	//if((VolumeDownFlag==0)&&(VolumeUpFlag==0))
   			//{
   		if((INT0Count>=150)&&(INT0Count<180))
   			{INT0TimehSum+=INT0Timeh;
   			}
   			if(INT0Count==180)
   				{
   					if(hptype_on==2)
   						 {
   					if((INT0TimehSum>75)&&(INT0TimehSum<100))
   						{VOLUMEUP=0;
  	     	     VolumeUpFlag=1;
   						}
   					if((INT0TimehSum>100)&&(INT0TimehSum<120))
   						{VOLUMEDOWN=0;
  	     	     VolumeDownFlag=1;
   						}	
   					else
   						INT0TimehSum=0;		
   					}
   					if(hptype_on==1)
   				   						 {
   				   					if((INT0TimehSum>50)&&(INT0TimehSum<70))
   				   						{VOLUMEUP=0;
   				  	     	     VolumeUpFlag=1;
   				   						}
   				   					if((INT0TimehSum>80)&&(INT0TimehSum<100))
   				   						{VOLUMEDOWN=0;
   				  	     	     VolumeDownFlag=1;
   				   						}
   				   					else
   				   						INT0TimehSum=0;
   				   					}
   				}
   			//}
   		/*if((VolumeDownFlag==0)&&(VolumeUpFlag==0))
   					{
   			if((INT0Count>=180)&&(INT0Count<210))
   			{INT0TimehSum+=INT0Timeh;
   			}
   			if(INT0Count==210)
   				{if(hptype_on==2)
   						 {
   					if((INT0TimehSum>80)&&(INT0TimehSum<100))
   						{VOLUMEUP=0;
  	     	     VolumeUpFlag=1;
   						}
   					if((INT0TimehSum>100)&&(INT0TimehSum<120))
   						{VOLUMEDOWN=0;
  	     	     VolumeDownFlag=1;
   						}	
   					else
   						INT0TimehSum=0;	
   					}	
   						if(hptype_on==1)
   				   						 {
   				   					if((INT0TimehSum>50)&&(INT0TimehSum<70))
   				   						{VOLUMEUP=0;
   				  	     	     VolumeUpFlag=1;
   				   						}
   				   					if((INT0TimehSum>80)&&(INT0TimehSum<100))
   				   						{VOLUMEDOWN=0;
   				  	     	     VolumeDownFlag=1;
   				   						}
   				   					else
   				   						INT0TimehSum=0;
   				   					}
   				}
   			}*/
goto INT_EXIT;   				
 

INT_RELEASE:
	INT0StartCountFlag=0;
	INT0Count=0;
	INT0TimehSum=0;
	if(VolumeDownFlag)
		 {
	VolumeDownFlag=0;	 	
  VOLUMEDOWN=1;
   }
   if(VolumeUpFlag)
		 {
	VolumeUpFlag=0;	 	
  VOLUMEUP=1;
   }
INT_EXIT:   

  INT0Timeh=0;

//IE_EX0=1;
}




